name: deploy to itch

on:
  workflow_call:
    inputs:
      plattform:
        required: true
        type: string
      artifact:
        required: true
        type: string
      buildChannel:
        required: true
        type: string

jobs:
  deploy_job:
    name: Upload Artifact ${{ inputs.artifact }} to channel ${{ input.buildChannel }}
    runs-on: ubuntu-latest
    steps:
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build/${{ inputs.targetPlatform }}/${{ inputs.buildPath }}
          itchUsername: ${{secrets.ITCH_USERNAME}}
          itchGameId: ${{secrets.ITCH_GAME_ID}}
          buildChannel: ${{ inputs.buildChannel }}