name: CI and CD to Itch

on:
  push:
    branches:
      - main

jobs:
  buildAndTestForLinuxBasedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath: [game]
        targetPlatform: [WebGL, Android]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildName: ld51
          projectPath: ${{ matrix.projectPath }}
          versioning: Semantic
          unityVersion: auto
          targetPlatform: ${{ matrix.targetPlatform }}
          buildsPath: build
      - name: Display structure of build files
        run: ls -R
        working-directory: /home/runner

      - name: Upload to itch for webgl
        if: ${{ matrix.platform }} == WebGL
        uses: ./.github/workflows/deploy.yml
        with:
          plattform: ${{ matrix.platform }}
          artifact: ld51/index.html
          buildChannel: webgl

      - name: Upload to itch for android
        if: ${{ matrix.platform }} == Android
        uses: ./.github/workflows/deploy.yml
        with:
          plattform: ${{ matrix.platform }}
          artifact: ld51.apk
          buildChannel: android